typography_spectrum: 0.7870531128719449
color:
  brandStrength: 0.6363273507449776
  lightness: 0.10258348216302693
  saturation: 0.5045955451205373
  rhythmicContrast: 0.8381347148679197
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.5625526662915945
name: Michael Lavelle
title: Michael Lavelle
